#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

echo "Setting up your Mac..."

# Check for Oh My Zsh and install if we don't have it
if test ! $(which omz); then
  /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/HEAD/tools/install.sh)"
fi

# Check for Homebrew and install if we don't have it
if test ! $(which brew); then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

rm -rf $HOME./.zprofile
ln -sf $DOTFILES/zsh/zprofile $HOME/.zprofile

rm -rf $HOME./.zshrc
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

rm -rf $HOME./.config/nvim
ln -sf $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME./.gitconfig
ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig

# Install Sublime Text settings
cp -rf sublimetext/Packages ~/Library/Application\ Support/Sublime\ Text*/ 2> /dev/null
cp -rf sublimetext/'Installed Packages' ~/Library/Application\ Support/Sublime\ Text*/ 2> /dev/null

# Update Homebrew recipes
brew update

# Install all our dependencies with bundle (See Brewfile)
brew tap homebrew/bundle
brew bundle --file ./Brewfile

# Create a projects directories
mkdir $HOME/Herd
mkdir $HOME/Herd/laravelmodules
mkdir $HOME/Herd/packages
mkdir $HOME/Herd/dc-projects
mkdir $HOME/Herd/tallapps
mkdir $HOME/Herd/wip

# Clone Github repositories
./clone.sh

# Symlink the Mackup config file to the home directory
ln -s ./.mackup.cfg $HOME/.mackup.cfg

# Set macOS preferences - we will run this last because this will reload the shell
source ./.macos.sh



