#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME./.zprofile
ln -sf $DOTFILES/zsh/zprofile $HOME/.zprofile

rm -rf $HOME./.zshrc
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

rm -rf $HOME./.config/nvim
ln -sf $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/tmux.conf
# ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# rm -rf $HOME/.yabairc
# ln -s $DOTFILES/yabairc $HOME/.yabairc

# rm -rf $HOME/.skhdrc
# ln -s $DOTFILES/skhd/skhd $HOME/.skhdrc


