#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

echo "Setting up your Mac..."

# Check for Oh My Zsh and install if we don't have it
if test ! $(which omz); then
  /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/HEAD/tools/install.sh)"
fi

# Check for Homebrew and install if we don't have it
if test ! $(which brew); then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

rm -rf $HOME./.zprofile
ln -sf $DOTFILES/zsh/zprofile $HOME/.zprofile

rm -rf $HOME./.zshrc
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

rm -rf $HOME./.config/nvim
ln -sf $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/tmux.conf
# ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# rm -rf $HOME/.yabairc
# ln -s $DOTFILES/yabairc $HOME/.yabairc

# rm -rf $HOME/.skhdrc
# ln -s $DOTFILES/skhd/skhd $HOME/.skhdrc

# Update Homebrew recipes
brew update

# Install all our dependencies with bundle (See Brewfile)
brew tap homebrew/bundle
brew bundle --file ./Brewfile

# Set default MySQL root password and auth type
mysql -u root -e "ALTER USER root@localhost IDENTIFIED WITH mysql_native_password BY 'secret'; FLUSH PRIVILEGES;"

# Symlink the Mackup config file to the home directory
ln -s ./.mackup.cfg $HOME/.mackup.cfg

# Set macOS preferences - we will run this last because this will reload the shell
source ./.macos



