export PATH="$PATH:$HOME/Library/Application Support/JetBrains/Toolbox/scripts"
export PATH="$PATH:$HOME/.composer/vendor/bin"
export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"
eval "$(/opt/homebrew/bin/brew shellenv)"

# Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Shortcuts
alias gdr='cd ~/"Google Drive/My Drive"'
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias sit="cd ~/sites"

# Laravel and packages
alias a='php artisan'
alias pd='vendor/bin/pest --dirty'
alias pb='vendor/bin/pest --bail'
alias pr='vendor/bin/pest --retry'
alias pw='vendor/bin/pest --without-exception-handling'
alias ptc='XDEBUG_MODE=coverage ./vendor/bin/pest --coverage'
alias pttc='vendor/bin/pest --type-coverage'
alias t='clear && php artisan test'
alias tp='clear && php artisan test --parallel'
alias pi='./vendor/bin/pint'
alias s='./vendor/bin/sail'
alias sa='./vendor/bin/sail artisan'
alias st='./vendor/bin/phpstan analyse'
alias i='./vendor/bin/phpinsights'
alias nr='npm run'
alias nrs='npm run serve'
alias nrb='npm run build'
alias nrd='npm run dev'

# Show/hide hidden files in Finder
alias show='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'
alias hide='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'

# Host file
alias hostfile='sudo vi /etc/hosts'

# Flush Directory Service cache
alias flush="dscacheutil -flushcache && killall -HUP mDNSResponder"

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Composer
alias cu='composer update'
alias ci='composer install'
alias cda='composer dump-autoload -o'
alias cr='composer require'

# GIT

## Git add and commit
function gac()
{
   #usage gac . 'the message'
   git add $1 && git commit -m "$2"
}

alias g='git'
alias gc='git checkout'
alias gm='git merge'
alias gs='git status'
alias gsc='git switch -c'
alias gp='git push'
alias gpu='git pull'
alias nah='git reset --hard HEAD'
alias glog='git log --oneline --decorate --graph --all'

# Directories
alias ls='ls -ls -a'

# SSH
alias sshkey='cat ~/.ssh/id_rsa.pub'
alias sshconfig='vi ~/.ssh/config'
alias copykey='command cat ~/.ssh/id_rsa.public | pbcopy'

# Programs
alias vi='nvim'

## Run either Pest if installed otherwise use PHPUnit
function p() {
   if [ -f vendor/bin/pest ]; then
      vendor/bin/pest "$@"
   else
      vendor/bin/phpunit "$@"
   fi
}

## Run test with filter
function pf() {
   if [ -f vendor/bin/pest ]; then
      vendor/bin/pest --filter "$@"
   else
      vendor/bin/phpunit --filter "$@"
   fi
}
