# Added by Toolbox App
export PATH="$PATH:/Users/dave/Library/Application Support/JetBrains/Toolbox/scripts"
export PATH="$PATH:$HOME/.composer/vendor/bin"

# Set PATH, MANPATH, etc., for Homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"

function p() {
   if [ -f vendor/bin/pest ]; then
      vendor/bin/pest "$@"
   else
      vendor/bin/phpunit "$@"
   fi
}

function pf() {
   if [ -f vendor/bin/pest ]; then
      vendor/bin/pest --filter "$@"
   else
      vendor/bin/phpunit --filter "$@"
   fi
}

alias a='php artisan'
alias t='clear && php artisan test'
alias tp='clear && php artisan test --parallel'
alias pint='./vendor/bin/pint'
alias st='./vendor/bin/phpstan analyse --ansi --memory-limit=-1'
alias nr='npm run'

# Show/hide hidden files in Finder
alias show='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'
alias hide='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'

# PHP switcher
alias php8='valet use php@81'
alias php74='valet use php@74'
alias phpunit='vendor/bin/phpunit'
alias pest='vendor/bin/pestphp'

#valet
alias vs='valet secure'
alias tunnel='valet share -subdomain=dc -region=eu'

#host file
alias hostfile='sudo vi /etc/hosts'

#composer
alias cu='composer update'
alias ci='composer install'
alias cda='composer dump-autoload -o'
alias cr='composer require'

#git
function gac()
{
   #usage gac . 'the message'
   git add $1 && git commit -m "$2"
}

alias g='git'
alias gc='git checkout'
alias gm='git merge'
alias gs='git status'
alias gp='git push'
alias gpu='git pull'
alias gno='git reset --hard HEAD'
alias glog='git log --oneline --decorate --graph --all'

#directories
alias ls='ls -ls -a'
alias projects='cd ~/Documents/local/projects'
alias personal='cd ~/sites/personal'
alias wip='cd ~/sites/wip'
alias packages='cd ~/sites/packages'
alias blog='cd ~/sites/personal/dcblog'
alias cms='cd ~/sites/iw/cms'

#ssh
alias sshkey='cat ~/.ssh/id_rsa.pub'
alias sshconfig='vi ~/.ssh/config'
alias copykey='command cat ~/.ssh/id_rsa.public | pbcopy'
export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"
