export PATH="$PATH:$HOME/.composer/vendor/bin"
eval "$(/opt/homebrew/bin/brew shellenv)"

function p() {
   if [ -f vendor/bin/pest ]; then
      vendor/bin/pest "$@"
   else
      vendor/bin/phpunit "$@"
   fi
}

function pf() {
   if [ -f vendor/bin/pest ]; then
      vendor/bin/pest --filter "$@"
   else
      vendor/bin/phpunit --filter "$@"
   fi
}

alias pd='vendor/bin/pest --dirty'
alias pb='vendor/bin/pest --bail'
alias pr='vendor/bin/pest --retry'
alias a='php artisan'
alias t='clear && php artisan test'
alias tp='clear && php artisan test --parallel'
alias pi='./vendor/bin/pint'
alias s='./vendor/bin/sail'
alias sa='./vendor/bin/sail artisan'
alias st='./vendor/bin/phpstan analyse'
alias nr='npm run'

# Show/hide hidden files in Finder
alias show='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder'
alias hide='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder'

#host file
alias hostfile='sudo vi /etc/hosts'

#composer
alias cu='composer update'
alias ci='composer install'
alias cda='composer dump-autoload -o'
alias cr='composer require'

#git
function gac()
{
   #usage gac . 'the message'
   git add $1 && git commit -m "$2"
}

alias g='git'
alias gc='git checkout'
alias gm='git merge'
alias gs='git status'
alias gp='git push'
alias gpu='git pull'
alias gno='git reset --hard HEAD'
alias glog='git log --oneline --decorate --graph --all'

#directories
alias ls='ls -ls -a'

#ssh
alias sshkey='cat ~/.ssh/id_rsa.pub'
alias sshconfig='vi ~/.ssh/config'
alias copykey='command cat ~/.ssh/id_rsa.public | pbcopy'
export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"

#valet
alias vs='valet secure'
alias tunnel='valet share -subdomain=dc -region=eu'
