export PATH=~/.composer/vendor/bin:$PATH
eval "$(/opt/homebrew/bin/brew shellenv)"

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="fishy"
plugins=(git)
source $ZSH/oh-my-zsh.sh